### ISSUE TITLE
Rank Resets

### ISSUE THREAD

**Issue by ghost** [BeetoGuy/LevelUp#14]
used forge 2311
1-level up mining to rank 1
2-it uses up 5 levels
3-play for a bit
4-then look back and it's back to 0

**Comment by BeetoGuy** [comment]
Anything I should look at? Dimension changes or stuff like that?

**Comment by BeetoGuy** [comment]
Yeah, looks like dimension changes are what's doing it. For future reference, the rewrite has a different repo.

**Comment by BeetoGuy** [comment]
Fixed it, turns out that I accidentally labeled something as "static" when it shouldn't have been.

**Comment by ghost** [comment]
Thanks!

**Comment by dyachoksa** [comment]
The issue still reproduces  for version 1.12.1 of Minecraft.
